version: "3.3"
services:
  llserver_ecui_houbold:
    build: .

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    expose:
      - 8083
      - 8086
      - 8090
      - 2003
