# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.14.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.14.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Volumes/Data/markus/Programming/SpaceTeam/TXV_ECUI_LLServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Volumes/Data/markus/Programming/SpaceTeam/TXV_ECUI_LLServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.14.3/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.14.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Data/markus/Programming/SpaceTeam/TXV_ECUI_LLServer/CMakeFiles /Volumes/Data/markus/Programming/SpaceTeam/TXV_ECUI_LLServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Volumes/Data/markus/Programming/SpaceTeam/TXV_ECUI_LLServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TXV_ECUI_LLSERVER

# Build rule for target.
TXV_ECUI_LLSERVER: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TXV_ECUI_LLSERVER
.PHONY : TXV_ECUI_LLSERVER

# fast build rule for target.
TXV_ECUI_LLSERVER/fast:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/build
.PHONY : TXV_ECUI_LLSERVER/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/main.cpp.s
.PHONY : main.cpp.s

serialTest.o: serialTest.cpp.o

.PHONY : serialTest.o

# target to build an object file
serialTest.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/serialTest.cpp.o
.PHONY : serialTest.cpp.o

serialTest.i: serialTest.cpp.i

.PHONY : serialTest.i

# target to preprocess a source file
serialTest.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/serialTest.cpp.i
.PHONY : serialTest.cpp.i

serialTest.s: serialTest.cpp.s

.PHONY : serialTest.s

# target to generate assembly for a file
serialTest.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/serialTest.cpp.s
.PHONY : serialTest.cpp.s

src/Debug.o: src/Debug.cpp.o

.PHONY : src/Debug.o

# target to build an object file
src/Debug.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Debug.cpp.o
.PHONY : src/Debug.cpp.o

src/Debug.i: src/Debug.cpp.i

.PHONY : src/Debug.i

# target to preprocess a source file
src/Debug.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Debug.cpp.i
.PHONY : src/Debug.cpp.i

src/Debug.s: src/Debug.cpp.s

.PHONY : src/Debug.s

# target to generate assembly for a file
src/Debug.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Debug.cpp.s
.PHONY : src/Debug.cpp.s

src/HcpCommands.o: src/HcpCommands.cpp.o

.PHONY : src/HcpCommands.o

# target to build an object file
src/HcpCommands.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/HcpCommands.cpp.o
.PHONY : src/HcpCommands.cpp.o

src/HcpCommands.i: src/HcpCommands.cpp.i

.PHONY : src/HcpCommands.i

# target to preprocess a source file
src/HcpCommands.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/HcpCommands.cpp.i
.PHONY : src/HcpCommands.cpp.i

src/HcpCommands.s: src/HcpCommands.cpp.s

.PHONY : src/HcpCommands.s

# target to generate assembly for a file
src/HcpCommands.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/HcpCommands.cpp.s
.PHONY : src/HcpCommands.cpp.s

src/SequenceManager.o: src/SequenceManager.cpp.o

.PHONY : src/SequenceManager.o

# target to build an object file
src/SequenceManager.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/SequenceManager.cpp.o
.PHONY : src/SequenceManager.cpp.o

src/SequenceManager.i: src/SequenceManager.cpp.i

.PHONY : src/SequenceManager.i

# target to preprocess a source file
src/SequenceManager.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/SequenceManager.cpp.i
.PHONY : src/SequenceManager.cpp.i

src/SequenceManager.s: src/SequenceManager.cpp.s

.PHONY : src/SequenceManager.s

# target to generate assembly for a file
src/SequenceManager.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/SequenceManager.cpp.s
.PHONY : src/SequenceManager.cpp.s

src/Serial.o: src/Serial.cpp.o

.PHONY : src/Serial.o

# target to build an object file
src/Serial.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Serial.cpp.o
.PHONY : src/Serial.cpp.o

src/Serial.i: src/Serial.cpp.i

.PHONY : src/Serial.i

# target to preprocess a source file
src/Serial.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Serial.cpp.i
.PHONY : src/Serial.cpp.i

src/Serial.s: src/Serial.cpp.s

.PHONY : src/Serial.s

# target to generate assembly for a file
src/Serial.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Serial.cpp.s
.PHONY : src/Serial.cpp.s

src/Socket.o: src/Socket.cpp.o

.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i

.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s

.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/TXV_ECUI_LLSERVER.dir/build.make CMakeFiles/TXV_ECUI_LLSERVER.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... TXV_ECUI_LLSERVER"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... serialTest.o"
	@echo "... serialTest.i"
	@echo "... serialTest.s"
	@echo "... src/Debug.o"
	@echo "... src/Debug.i"
	@echo "... src/Debug.s"
	@echo "... src/HcpCommands.o"
	@echo "... src/HcpCommands.i"
	@echo "... src/HcpCommands.s"
	@echo "... src/SequenceManager.o"
	@echo "... src/SequenceManager.i"
	@echo "... src/SequenceManager.s"
	@echo "... src/Serial.o"
	@echo "... src/Serial.i"
	@echo "... src/Serial.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

